language: node_js
node_js:
 - 12.12.0
script:
  - npm run lint
after_success:
  - npm run deploy
notifications:
  email: false
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
branches:
  only:
    - master